# =======================================================================
#
#  This file is part of WebWidgets, a Python package for designing web
#  UIs.
#
#  You should have received a copy of the MIT License along with
#  WebWidgets. If not, see <https://opensource.org/license/mit>.
#
#  Copyright(C) 2025, mlaasri
#
# =======================================================================

name: "CD: Publish to TestPyPI"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+(.dev[0-9]+)?"
      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+(.dev[0-9]+)?"
      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+(.dev[0-9]+)?"
      - "[0-9]+.[0-9]+.[0-9].dev[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+(.dev[0-9]+)?"
      - "[0-9]+.[0-9]+.[0-9]+post[0-9]+(.dev[0-9]+)?"

jobs:
  ensure-main:
    if: github.event.base_ref == 'refs/heads/main'
    name: Ensure tag was pushed to main
    runs-on: ubuntu-latest
    steps:
    - name: Log that tag was pushed to main
      run: echo "Tag was pushed to main branch. Starting CD workflow."

  build:
    name: Build package
    needs: ensure-main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Install pypa/hatch
      run: python3 -m pip install hatch
    - name: Set version with hatch
      run: |
        # Using variable instead of GitHub-specific contexts
        TAG=$(git describe --tags --abbrev=0)
        echo "Setting version from tag: $TAG"
        hatch version $TAG
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish package to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/webwidgets
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/